language: node_js
sudo: false
node_js:
- '0.12'
before_install:
# obt v3 cannot be installed with npm > 2.7.5
- npm install -g npm@2.7.5
- npm install -g Financial-Times/origami-build-tools#node12
- obt install
script:
- obt test
- obt verify
notifications:
  hipchat:
    rooms:
      secure: OaeA99xzMFRy7XZG8sbe7JWHoC1k4OEd8Po4WFHojFHHJ+nYWKyEnA9Ob0kf8OG9NlPDPo4/zXpD4ETaAmD41UtyQGbuPKvNMGju1ebO9MxP5T4aof07FlxWw2rdA2Wf3dT9dy39pS7SaU1dZPuIlFvIXRCgXksJBI0gnmtfheFfA8VlS/veIvdKXEyde+WTzpU42KBBSZDDJkMNd3liDlpfmHSPuZojqu6rqnRWSq9i7IMjyOCWbjbHC/ODjYroeBMS7/mpueQxZJm5HZc2SO1JK/oLLMFocE/WElYuzpUGTnlZiPFFpptVLbmepYnzLfT/7XHdeLXzAR44rxeEY5WIIIhW67DvkUJ8p8+C7+dEW1uiLCXrrNIt9dAiQNyiDrb7UvQ6nOm76Dfbma/C7nexkPgZKxHaxHbddr2hvxZYBIE2F2EeUo5Shh4KbzXbzDw/yEysN1QRJjGWPRyIOai+jbto5lpzcNnuxBV995TuD03i/yuMf8cIUZ5LZMaqHoW447Ez0wSPOMRL73ZCxRhdVp8niIUDaL/V2BgUlWjbiIQxaTudHJRQP6oVdfMWDmV7kX+TLIIpKmaKbkreBk7/t9+0ufmG6bcqmci+QhY4OF0x0N3jbX/UmbFai7Ir1V4yaR3qrecDteev22GsNiLhpohal4DjfRlzT/35D4k=
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
